Upgrade node-forge to 0.10.0
parse-community/node-apn pull request #18
Opened 2020-09-08 15:59 UTC by davimacedo

2020-09-09 01:34 UTC, dplewis requested changes

2020-09-09 01:34 UTC, dplewis commented on package.json
> +    "node-forge": "^0.10.0",
Can you pin the packages?

2020-09-09 15:32 UTC, davimacedo commented on package.json
> +    "node-forge": "^0.10.0",
done

2020-09-09 21:03 UTC, davimacedo commented
I updated all dependencies to the latest version but the tests are failing for node 8. I believe we should support only node >= 10. Thoughts? @dplewis

2020-09-17 16:10 UTC, closed without merging

2020-09-17 17:18 UTC, Ashoat commented
@davimacedo, any context as to why you closed this? There appears to be a [security issue](https://github.com/advisories/GHSA-92xj-mqp7-vmcj) with the old `node-forge`, so would be great to update it.

2020-09-17 17:22 UTC, TomWFox commented
@Ashoat Davi opened a new PR #19

2020-09-17 17:25 UTC, Ashoat commented
Ah yeah #20, I missed that. Thanks!